<?php
/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();

$requiredAttributes = ['dimensions', 'colour', 'material'];

$_description = $_product->getDescription();
$_description = strip_tags($_description);
$firstSentence = strtok($_description, '.').'.';
?>

<?php if ($_additional = $block->getAdditionalData()) : ?>
    <div class="product-attributes">
        <ul>
            <?php foreach ($_additional as $_data) : ?>
                <?php if (in_array($_data['code'], $requiredAttributes)) : ?>
                    <li>
                        <strong><?= $block->escapeHtml($_data['label']) ?>:</strong>
                        <?= $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<?php if (!empty($firstSentence)): ?>
    <div class="product-short-description">
        <?= $block->escapeHtml($firstSentence) ?>
    </div>
<?php endif; ?>
